### ISSUE TITLE
Question regarding usage in Ada Programming wikibook

### ISSUE THREAD

**Issue by mgrojo** [reznikmm/adalib#2]
Hi Maxim,

I am thinking in generating some stub pages for the Ada Programming wikibook about all the missing Ada Standard Library units. I'd like to use your specifications, since they are already extracted and have correct syntax. You can see an example of what I'm trying to generate in [Ada.Calendar page](https://en.wikibooks.org/wiki/Ada_Programming/Libraries/Ada.Calendar).

I assume that this will be in accordance to Ada Reference Manual copyright and your licence. I've written the source of the specification in the page history. Do you have any preference on that regard, for example, a direct link to this repository on every page?

**Comment by reznikmm** [comment]
Hi @mgrojo 
The page looks great! I don't have any preferences.

As for me, specifications from standard library lacks documentation. May be you have some idea how to improve them in this aspect?

**Comment by mgrojo** [comment]
Ideally, each page in the wikibook for a Standard Library unit should contain hints on usage and examples. A good example is the page for [Ada.Directories](https://en.wikibooks.org/wiki/Ada_Programming/Libraries/Ada.Directories#Exceptions). But that requires a big manual effort. For the time being, I'd like to add a stub for each unit, so it is already a useful resource, with the specification, the links to the Reference Manual and other pages where to find examples of the unit. The stub should facilitate anyone to add the missing hints and examples.

**Comment by mgrojo** [comment]
I think I've finished the stub generator for the wikibook. I've added links to open-source implementations (FSF GNAT and drake) and a reference to the standard in which it was included. Do you have any idea to improve it with any other information? I haven't found a way to search for code examples in projects hosted by sourceforge.

You can close this issue whenever you want.
